Call/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('callapp.urls')),

]

callapp/urls.py
from django.urls import path
from callapp import views as callapp_views
app_name = "callapp"
urlpatterns = [

    path('',callapp_views.home_page , name='home_page'),
    path('intiate-call/',callapp_views.intiate_call , name='intiate_call'),
    path('call-report/',callapp_views.call_report , name='call_report'),
    path('delete/<int:id>/<str:number>',callapp_views.delete_call , name='delete_call'),
   
    
]

callapp/models.py
from django.db import models

# Create your models here.
class CallLog(models.Model):
    id = models.IntegerField(primary_key=True)
    from_number=models.CharField(max_length=10,null=True)
    to_number=models.CharField(max_length=10,null=True)
    calling_time=models.TimeField()

callapp/views.py
from django.shortcuts import render , redirect
from django.core.paginator import Paginator
from .models import CallLog
from django.contrib import messages
import datetime


# Create your views here.

# this view rendering home page
def home_page(request):
    return render(request,"callapp/make_call.html")

# this view save call in database table, CallLog
def intiate_call(request):
    if request.method == 'POST':
        from_number = request.POST.get('from')
        to_number = request.POST.get('to')
        if from_number!=to_number:# both number are different
            submission_time=datetime.datetime.now()
            CallLog(from_number=from_number,to_number=to_number,calling_time=submission_time).save()
            messages.success(request, "Call successfulil made!." )
        else:                    # both number are same
            messages.error(request, "You can't make call to same numbers!" )
    return render(request, 'callapp/make_call.html')
    
# this view collect all call detail for particular number 
def call_report(request):
    number=request.GET['phone']    
    calls=CallLog.objects.all()
    lst=[]                         # empty list is created
    for call in calls:
        if call.from_number==number or call.to_number==number:
            lst.append(call)       # appending only those call , which contain this number

    paginator = Paginator(lst, 11) # paginator object created for 10 calls
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
                                
    return render(request,"callapp/call_detail.html",{"calls":page_obj,'number':number})
                                
# delete the particular call with id(primary key)       
def delete_call(request,id,number):
    obj_to_delete = CallLog.objects.get(id=id)
    obj_to_delete.delete()                        
    url = '/call-report/?phone={}'.format(number) # build the new URL with the variable as a parameter
    return redirect(url)     # redirect to the new URL

callapp/templates/callapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>FreJun Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/html-duration-picker@latest/dist/html-duration-picker.min.js"></script>
    
  </head>
  <body>
    {% block content%}
    {# child template #}
    {% endblock %} 
  </body>
</html>

callapp/templates/callapp/call_detail.html
{% extends "callapp/base.html" %}{# Inheriting Parent template #}
{% block content %}

{# display pagination links #}
<div class="pagination " style="margin-left: 46%;">
    <span class="step-links">
        {% if calls.has_previous %}
            <a href="?page=1&phone={{number}}">&laquo; first</a>
            <a href="?page={{ calls.previous_page_number }}&phone={{number}}">previous</a>
            <br>
        {% endif %}
        <span class="current-page">
            Page {{ calls.number }} of {{ calls.paginator.num_pages }}.
        </span>
        <br>
        {% if calls.has_next %}
            <a href="?page={{ calls.next_page_number }}&phone={{number}}">&laquo;next</a>
            <a href="?page={{ calls.paginator.num_pages }}&phone={{number}}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{# Creating table to show call report #}
<table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">from</th>
        <th scope="col">to</th>
        <th scope="col">timing</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
        {% for call in calls %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ call.from_number }}</td>
            <td>{{ call.to_number }}</td>
            <td>{{ call.calling_time }}</td>
            <td><a href="{% url 'callapp:delete_call' id=call.id number=number %}">Delete</a></td>
          </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

callapp/templates/callapp/make_call.html
{% extends "callapp/base.html" %}{# Inheriting Parent template #}
{% block content %}

{# Alert message while making call #}
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      {{ message }}
  </div>
</div>
{% endfor %}

<div class="container mt-4">
    <div class="row">
        <div class="col-4 offset-2">
            <div class="call-form" style="width: 250px;">
            <h1>Make A Call</h1>{# Creating form to make call #}
            <form action="{% url 'callapp:intiate_call' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="mobile1">From Number:</label>
                    <input type="tel" id="mobile1" name="from" pattern="[0-9]{10}" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="mobile2">To Number:</label>
                    <input type="tel" id="mobile2" name="to" pattern="[0-9]{10}" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
        <div class="col-4 offset-1">
            <div class="report-form" style="width: 290px;">
                <h1>Get Call Report</h1>{# Creating form to get call details #}
                <form action="{% url 'callapp:call_report' %}" method="GET">
                    <div class="form-group">
                        <label for="phone">Mobile Number:</label>
                        <input type="tel" id="phone" name="phone" pattern="[0-9]{10}" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>

    </div>
</div>


{% endblock %}